# Experiment 1: Introduction to Python for Data Analytics

**Course:** Data Analysis and Visualization (DAV) Lab

## Aim
To understand the basics of **NumPy** and **Pandas**: array operations, DataFrame creation, indexing and slicing.

## Tools Used
Python 3, NumPy, Pandas

## 1. Importing Libraries

In [1]:
import numpy as np
import pandas as pd

print("NumPy version :", np.__version__)
print("Pandas version:", pd.__version__)

NumPy version : 2.4.4
Pandas version: 3.0.2

## Part A: NumPy Basics

### 1.1 Creating Arrays

In [2]:
a = np.array([10, 20, 30, 40, 50])            # 1-D array
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # 2-D array

print("1-D array:", a)
print("2-D array:\n", b)

1-D array: [10 20 30 40 50]
2-D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

In [3]:
print("zeros  :\n", np.zeros((2, 3)))
print("ones   :\n", np.ones((2, 3)))
print("arange :", np.arange(0, 20, 4))
print("linspace:", np.linspace(0, 1, 5))
print("identity:\n", np.eye(3))

zeros  :
 [[0. 0. 0.]
 [0. 0. 0.]]
ones   :
 [[1. 1. 1.]
 [1. 1. 1.]]
arange : [ 0  4  8 12 16]
linspace: [0.   0.25 0.5  0.75 1.  ]
identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

### 1.2 Array Attributes

In [4]:
print("Shape    :", b.shape)
print("Dimensions:", b.ndim)
print("Size     :", b.size)
print("Data type:", b.dtype)

Shape    : (3, 3)
Dimensions: 2
Size     : 9
Data type: int64

### 1.3 Array Operations

In [5]:
x = np.array([1, 2, 3, 4])
y = np.array([10, 20, 30, 40])

print("x + y :", x + y)
print("y - x :", y - x)
print("x * y :", x * y)
print("y / x :", y / x)
print("x ** 2:", x ** 2)
print("x * 5 (broadcasting):", x * 5)

x + y : [11 22 33 44]
y - x : [ 9 18 27 36]
x * y : [ 10  40  90 160]
y / x : [10. 10. 10. 10.]
x ** 2: [ 1  4  9 16]
x * 5 (broadcasting): [ 5 10 15 20]

In [6]:
marks = np.array([[78, 85, 90], [62, 70, 68], [88, 92, 95], [55, 60, 58]])

print("Sum of all marks   :", marks.sum())
print("Mean of all marks  :", marks.mean())
print("Max / Min          :", marks.max(), "/", marks.min())
print("Column-wise mean   :", marks.mean(axis=0))
print("Row-wise total     :", marks.sum(axis=1))
print("Std deviation      :", marks.std().round(2))

Sum of all marks   : 901
Mean of all marks  : 75.08333333333333
Max / Min          : 95 / 55
Column-wise mean   : [70.75 76.75 77.75]
Row-wise total     : [253 200 275 173]
Std deviation      : 13.99

In [7]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Element-wise product:\n", A * B)
print("Matrix multiplication:\n", A @ B)
print("Transpose of A:\n", A.T)

Element-wise product:
 [[ 5 12]
 [21 32]]
Matrix multiplication:
 [[19 22]
 [43 50]]
Transpose of A:
 [[1 3]
 [2 4]]

### 1.4 Indexing and Slicing of Arrays

In [8]:
arr = np.arange(10, 100, 10)
print("Array        :", arr)
print("arr[0]       :", arr[0])
print("arr[-1]      :", arr[-1])
print("arr[2:6]     :", arr[2:6])
print("arr[::2]     :", arr[::2])
print("arr[::-1]    :", arr[::-1])

Array        : [10 20 30 40 50 60 70 80 90]
arr[0]       : 10
arr[-1]      : 90
arr[2:6]     : [30 40 50 60]
arr[::2]     : [10 30 50 70 90]
arr[::-1]    : [90 80 70 60 50 40 30 20 10]

In [9]:
m = np.arange(1, 17).reshape(4, 4)
print("Matrix:\n", m)
print("m[1, 2]      :", m[1, 2])
print("Row 2        :", m[2])
print("Column 1     :", m[:, 1])
print("Sub-matrix m[1:3, 1:3]:\n", m[1:3, 1:3])

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
m[1, 2]      : 7
Row 2        : [ 9 10 11 12]
Column 1     : [ 2  6 10 14]
Sub-matrix m[1:3, 1:3]:
 [[ 6  7]
 [10 11]]

In [10]:
# Boolean masking
print("Elements of m greater than 10:", m[m > 10])
print("Even elements:", m[m % 2 == 0])

Elements of m greater than 10: [11 12 13 14 15 16]
Even elements: [ 2  4  6  8 10 12 14 16]

## Part B: Pandas Basics

### 2.1 Series

In [11]:
s = pd.Series([85, 90, 78, 92], index=["Maths", "Physics", "Chemistry", "English"])
print(s)
print("\nMean score:", s.mean())
print("Physics score:", s["Physics"])

Maths        85
Physics      90
Chemistry    78
English      92
dtype: int64

Mean score: 86.25
Physics score: 90

### 2.2 DataFrame Creation

In [12]:
data = {
    "Name":       ["Aarav", "Diya", "Rohan", "Sneha", "Kiran", "Meera"],
    "Department": ["CSE", "ECE", "CSE", "ME", "ECE", "CSE"],
    "Maths":      [85, 78, 92, 66, 74, 88],
    "Physics":    [80, 82, 90, 70, 68, 91],
    "Attendance": [92, 85, 96, 70, 78, 94],
}
df = pd.DataFrame(data)
df

    Name Department  Maths  Physics  Attendance
0  Aarav        CSE     85       80          92
1   Diya        ECE     78       82          85
2  Rohan        CSE     92       90          96
3  Sneha         ME     66       70          70
4  Kiran        ECE     74       68          78
5  Meera        CSE     88       91          94

In [13]:
# DataFrame from a list of lists and from a NumPy array
df2 = pd.DataFrame([[1, "A"], [2, "B"], [3, "C"]], columns=["ID", "Grade"])
df3 = pd.DataFrame(np.random.default_rng(1).integers(1, 100, (3, 4)), columns=list("WXYZ"))
print(df2, "\n")
print(df3)

   ID Grade
0   1     A
1   2     B
2   3     C

    W   X   Y   Z
0  47  51  75  95
1   4  15  82  94
2  25  31  87  42

In [14]:
print("Shape  :", df.shape)
print("Columns:", list(df.columns))
print("Index  :", df.index)
df.dtypes

Shape  : (6, 5)
Columns: ['Name', 'Department', 'Maths', 'Physics', 'Attendance']
Index  : RangeIndex(start=0, stop=6, step=1)

Name            str
Department      str
Maths         int64
Physics       int64
Attendance    int64
dtype: object

### 2.3 Indexing and Slicing of DataFrames

In [15]:
# Selecting columns
df["Name"]

0    Aarav
1     Diya
2    Rohan
3    Sneha
4    Kiran
5    Meera
Name: Name, dtype: str

In [16]:
df[["Name", "Maths"]]

    Name  Maths
0  Aarav     85
1   Diya     78
2  Rohan     92
3  Sneha     66
4  Kiran     74
5  Meera     88

In [17]:
# Selecting rows by position (iloc) and by label (loc)
print("First row (iloc[0]):")
print(df.iloc[0], "\n")
df.loc[2, "Name"]

First row (iloc[0]):
Name          Aarav
Department      CSE
Maths            85
Physics          80
Attendance       92
Name: 0, dtype: object

'Rohan'

In [18]:
# Slicing rows and columns
print("Rows 1 to 3 (iloc):")
print(df.iloc[1:4], "\n")
print("Rows 0-2, columns Name to Physics (loc):")
df.loc[0:2, "Name":"Physics"]

Rows 1 to 3 (iloc):
    Name Department  Maths  Physics  Attendance
1   Diya        ECE     78       82          85
2  Rohan        CSE     92       90          96
3  Sneha         ME     66       70          70

Rows 0-2, columns Name to Physics (loc):

    Name Department  Maths  Physics
0  Aarav        CSE     85       80
1   Diya        ECE     78       82
2  Rohan        CSE     92       90

In [19]:
# Conditional selection (filtering)
df[df["Maths"] > 80]

    Name Department  Maths  Physics  Attendance
0  Aarav        CSE     85       80          92
2  Rohan        CSE     92       90          96
5  Meera        CSE     88       91          94

In [20]:
df[(df["Department"] == "CSE") & (df["Attendance"] > 90)]

    Name Department  Maths  Physics  Attendance
0  Aarav        CSE     85       80          92
2  Rohan        CSE     92       90          96
5  Meera        CSE     88       91          94

### 2.4 Basic Operations on DataFrames

In [21]:
df["Total"] = df["Maths"] + df["Physics"]
df["Average"] = df["Total"] / 2
df.sort_values("Total", ascending=False)

    Name Department  Maths  Physics  Attendance  Total  Average
2  Rohan        CSE     92       90          96    182     91.0
5  Meera        CSE     88       91          94    179     89.5
0  Aarav        CSE     85       80          92    165     82.5
1   Diya        ECE     78       82          85    160     80.0
4  Kiran        ECE     74       68          78    142     71.0
3  Sneha         ME     66       70          70    136     68.0

In [22]:
df.groupby("Department")[["Maths", "Physics", "Attendance"]].mean().round(2)

            Maths  Physics  Attendance
Department
CSE         88.33     87.0        94.0
ECE         76.00     75.0        81.5
ME          66.00     70.0        70.0

## Result
NumPy arrays were created, manipulated, indexed and sliced; Pandas Series and DataFrames were created and accessed using `iloc`, `loc`, column selection and boolean filtering.

## Conclusion
NumPy gives fast, vectorised numerical operations, while Pandas provides labelled tabular structures. Together they form the base for every later data analytics experiment.